#!/bin/bash

# Hardcoded list of directories and files
declare -A conf_list
conf_list[Neovim]="$HOME/.config/nvim/init.lua"
conf_list[Qtile]="$HOME/.config/qtile/config.py"

num_entries=${#conf_list[@]}

# Extract the keys from the associative array
key_list=$(printf "%s\n" "${!conf_list[@]}")

# Run rofi in dmenu mode
chosen_key=$(echo -e "$key_list" | rofi -dmenu -i -p "Config" -theme-str "window {width: 20em;} listview {lines: $num_entries;}")

# Open selected file in Neovim within Alacritty
if [ -n "$chosen_key" ]; then
    file_path="${conf_list[$chosen_key]}"
    directory=$(dirname "$file_path")
    $terminal -e bash -c "cd '$directory'; nvim '$file_path'" &
fi

