#!/bin/bash

# Define the options for dmenu
declare -A options
options[Shutdown]="systemctl poweroff"
options[Logout]="loginctl terminate-session $XDG_SESSION_ID"
options[Suspend]="systemctl suspend"
options[Reboot]="systemctl reboot"

num_entries=${#options[@]}

# Prompt the user to select an option using dmenu
selected_option=$(printf '%s\n' "${!options[@]}" | rofi -theme-str "window {width: 20em;} listview {lines: $num_entries;}" -dmenu -i -p "Select an option:")

# Perform the selected action
if [ -n "$selected_option" ]; then
    eval "${options[$selected_option]}" &
fi
